### ISSUE TITLE
add SPI and/or QSPI

### ISSUE THREAD

**Issue by davideschiavone** [esl-epfl/x-heep#12]
SPI can be vendorized from https://github.com/lowRISC/opentitan/tree/master/hw/ip/spi_host, see https://docs.opentitan.org/hw/ip/spi_host/doc/

- [x] add HW
- [ ] add SW
- [ ] test it

**Comment by davideschiavone** [comment]
work in progress here: https://github.com/davideschiavone/core-v-mini-mcu/pull/31

**Comment by davideschiavone** [comment]
in progress in #44 , #31 deprecated as merged in #44, however, still there in case of retro-fronts

**Comment by davideschiavone** [comment]
HW done in #59

**Comment by benoitdenkinger** [comment]
SW and test in #94
