### ISSUE TITLE
OpenTitan SPI host RTL update

### ISSUE THREAD

**Issue by benoitdenkinger** [esl-epfl/x-heep#125]
The vendorized OT SPI host RTL implementation as a one cycle latency between the write to the command register and the ready bit of the status register, requiring an extra nop before reading it in the bootrom for example.

- [ ] Check the latest implementation here [https://github.com/lowRISC/opentitan](url)
- [ ] Check the necessity for this extra cycle, otherwise update the RTL (contribution to openTitan?)

**Comment by davideschiavone** [comment]
#158
