### ISSUE TITLE
FreeRTOS option in sw/Makefile

### ISSUE THREAD

**Issue by fimtrey** [esl-epfl/x-heep#204]
In the MAKEFILE it's specified to use the `LINKER` option to use the FreeRTOS library 
```make
# Linker options are 'on_chip' (default),'flash_load','flash_exec','freertos'
LINKER   ?= on_chip
```
But `LINKER=freertos` doesn't work.
> Linker specification is not correct

As fare as I can see an option like `USE_FREERTOS` could replace the following `if`s in the `sw/CMakeLists.txt` to use FreeRTOS with other applications.

```cmake
if(${PROJECT} MATCHES "freertos")
   # ...
endif()
```

**Comment by davideschiavone** [comment]
assigned to @JoseCalero

**Comment by davideschiavone** [comment]
can we pls delete it from the SW and Makefile ?

**Comment by JoseCalero** [comment]
Yes, this is being committed to my PR for this week

**Comment by fimtrey** [comment]
What command can I run to link FreeRTOS?

**Comment by JoseCalero** [comment]
you just need to rename your application folder as `i2s_freertos`

**Comment by fimtrey** [comment]
makes sense
