### ISSUE TITLE
add bootROM

### ISSUE THREAD

**Issue by davideschiavone** [esl-epfl/x-heep#22]
- [ ] add ROM RTL
- [ ] add ROM SW
- [ ] add ROM selection and pins
- [ ] update TB

**Comment by davideschiavone** [comment]
At the moment we did not define what we want to do it yet - it's gonna be one of the last tasks

**Comment by benoitdenkinger** [comment]
Ok, so just adding a ROM for now. What is "add the ROM selection and pins"?

**Comment by davideschiavone** [comment]
we want to add 1 or 2 pins externally, say, bootsel_i, that are gonna read by the boot software.
Then the core either waits for jtag to program the memory, or read from SPI to load the code to the on chip ram, or whatever else we decide to do :)

**Comment by davideschiavone** [comment]
in progress in #44

**Comment by davideschiavone** [comment]
done in #59
