### ISSUE TITLE
Power gating core app needs to use different GPIOs

### ISSUE THREAD

**Issue by JuanSapriza** [esl-epfl/x-heep#276]
Currently the `example_power_gating_core` application uses GPIOs 30 and 31 to trigger an interrupt to wake the core up. 

Those GPIOs are no longer accessible in the FPGA (I think they were used for the SPI2). The app should be modified to consider this new situation.

**Comment by davideschiavone** [comment]
this part of the application should just be removed when `#ifndef PYNQ` as it is just for the testbench

@simone-machetti pls check that works on Verilator and add the #ifndef to the latest part pls :)

**Comment by davideschiavone** [comment]
this is fixed now
