### ISSUE TITLE
Warning missing: Some apps only available for Verilator

### ISSUE THREAD

**Issue by JuanSapriza** [esl-epfl/x-heep#277]
The `example_power_gating_external` and `example_virtual_flash` applications do not work on FPGA or simulators other than Verilator. A warning should be raised in when the program is compiled for FPGA. 
```c
#ifndef TARGET_SIM
    #pragma message ( "This application only works on Verilator" )
#endif
```

**Comment by davideschiavone** [comment]
should be done now
