### ISSUE TITLE
CI to test compilation using differents configurations

### ISSUE THREAD

**Issue by JuanSapriza** [esl-epfl/x-heep#280]
Right now, we have a CI that tests all apps using the default configurations (target: sim, linker: on_chip, etc)

We would like to have a script like the one in `X-HEEP/scripts/compile_all_apps.sh`. 

Note that this app has a bug as arrays should be defined as 
```
declare -a arr=("element1" "element2" "element3")
for i in "${arr[@]}"
do
    ....
done
```

I have tested this feature on my local computer using a variation of the script in the CI and it takes just slightly longer than the original one (the huge container configuration overhead is the real bottleneck).

**Comment by davideschiavone** [comment]
@JuanSapriza , can we close this?

**Comment by JuanSapriza** [comment]
If we merge #359
