### ISSUE TITLE
CI to simulate applications

### ISSUE THREAD

**Issue by JuanSapriza** [esl-epfl/x-heep#281]
We would like a CI that actually simulates applications, not only compiles them. 

This presents several challenges: 
* Install Verilator on the container.
* Eventually, if the size of the container grows too much, host the runner ourselves.
* Modify all apps to make sure they all return at some point, and return a certain value. 
* Warn that running on Verilator does not guarantee working for other configurations.

**Comment by JuanSapriza** [comment]
This is related to #341 (which implements the script that then needs to be integrated into the CI)

**Comment by davideschiavone** [comment]
this has been done
