### ISSUE TITLE
Docker container for X-HEEP

### ISSUE THREAD

**Issue by JuanSapriza** [esl-epfl/x-heep#282]
We would like to have a Docker image containing all necessary tools for X-HEEP, to make it as plug and play as possible. 

This can start from the one published on the ESL Github page for the app compilation CI.  

In it we could have Verilator, but should be careful with any proprietary files.

**Comment by Guilherme-Soares-Sequeira** [comment]
Seeing as this is still opened, I figured I'd let you know we wrote a dockerfile for X-HEEP targeting the cv32e40p core and core-v toolchain, which may prove useful for this issue. It can be found [here](https://github.com/specs-feup/riscv-ai-extensions/tree/main/pulp-xheep-cv32e40p-docker).

**Comment by davideschiavone** [comment]
this has been done now
