### ISSUE TITLE
DMA transaction type not given by targets

### ISSUE THREAD

**Issue by JuanSapriza** [esl-epfl/x-heep#335]
Currently the transaction type is assigned from the source type. This was thought this way to allow targets to be "symmetrical" and "interchangeable".

Since the DMA only supports one data size, both should necessarily be the same. If you are already going to change the targets, changing also the type sounds reasonable. 

Make the type only in the transaction and not the targets to make the logic simpler and more easy to understand for the user.

**Comment by davideschiavone** [comment]
with #498 , the SRC and DST will have 2 different types - so closing this issue when that PR will be merged
