### ISSUE TITLE
App build failure in `run-helloworld` target

### ISSUE THREAD

**Issue by StMiky** [esl-epfl/x-heep#411]
## Description
When calling the "all-in-one" (`run-helloworld` and `run-blinkfreertos`) targets on a clean clone of X-HEEP,  the software build process enters a recursive loop where infinite file descriptors are opened on the host system, eventually resulting in a build failure. Building the same applications with `make app PROJECT=...` works as expected.

## Proposed solution
Explicitly specifying the `SOURCE` when calling `make -C sw` in these tasks, like it's done in the `app` target, seems to resolve the issue. A pull request implementing this fix is being prepared.

## Host system
- OS: CentOS 8
- `cmake`: 3.20.2
- `gcc`: 12.1.1

**Comment by JoseCalero** [comment]
should be fixed by #422
