### ISSUE TITLE
Two files needed to compile in external application

### ISSUE THREAD

**Issue by JuanSapriza** [esl-epfl/x-heep#429]
Today @benoitdenkinger noted that if he had an external application composed of two files: 
```
BASE
├── sw
│   ├── applications
│   │   └── my_app
│   ...		├── main.c	
		└── dummy.h
```
The program compiles successfully, even if dummy is not even included. 
This does not happen if `dummy.h` is not present. 
@benoitdenkinger could you provide us the output that you get from doing so? 

I remember one of the issues was that the `SOURCE_PATH` variable was changed to `ROOT_PROJECT`.   

Might be related to #358 @JoseCalero

**Comment by benoitdenkinger** [comment]
When I have only a single main.c file I get the following (this is with the heepsilon platform):

ln -sf ../hw/vendor/esl_epfl_x_heep/sw/build sw/build
Your relative sources path is ../../../../sw/
make -C hw/vendor/esl_epfl_x_heep/ app SOURCE=../../../../sw/
make[1]: Entering directory '/home/benoit/ESL/Projects/HEEPsilon/hw/vendor/esl_epfl_x_heep'
USING VENV
rm -rf sw/build
make -C sw PROJECT=cgra_size TARGET=sim LINKER=on_chip COMPILER=gcc COMPILER_PREFIX=riscv32-unknown- ARCH=rv32imc SOURCE=../../../../sw/
make[2]: Entering directory '/home/benoit/ESL/Projects/HEEPsilon/hw/vendor/esl_epfl_x_heep/sw'
$You are executing from: /home/benoit/ESL/Projects/HEEPsilon/hw/vendor/esl_epfl_x_heep/sw
$You are fetching sources from /home/benoit/ESL/Projects/HEEPsilon/sw 
if [ ! -d build ] ; then mkdir build ; fi
cd build;  \
	cmake \
	    -G "Unix Makefiles" \
		-DCMAKE_TOOLCHAIN_FILE=../cmake/riscv.cmake \
		-DROOT_PROJECT=/home/benoit/ESL/Projects/HEEPsilon/hw/vendor/esl_epfl_x_heep/sw/ \
		-DSOURCE_PATH=/home/benoit/ESL/Projects/HEEPsilon/sw/ \
		-DTARGET=sim \
		-DPROJECT:STRING=cgra_size \
		-DRISCV:STRING=/home/benoit/Tools/riscv \
		-DINC_FOLDERS:STRING=/home/benoit/ESL/Projects/HEEPsilon/hw/vendor/esl_epfl_x_heep/sw/device/target/sim/ \
		-DLINK_FOLDER:STRING=/home/benoit/ESL/Projects/HEEPsilon/hw/vendor/esl_epfl_x_heep/sw/linker \
		-DLINKER:STRING=on_chip \
		-DCOMPILER:STRING=gcc \
		-DCOMPILER_PREFIX:STRING=riscv32-unknown- \
	    ../ 
-- The ASM compiler identification is GNU
-- Found assembler: /home/benoit/Tools/riscv/bin/riscv32-unknown-elf-gcc
-- The C compiler identification is GNU 11.1.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /home/benoit/Tools/riscv/bin/riscv32-unknown-elf-gcc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- [INFO] -I /home/benoit/ESL/Projects/HEEPsilon/sw/device/lib/base     -I /home/benoit/ESL/Projects/HEEPsilon/sw/device/lib/base     -I /home/benoit/ESL/Projects/HEEPsilon/sw/device/lib/base     -I /home/benoit/ESL/Projects/HEEPsilon/sw/device/lib/base     -I /home/benoit/ESL/Projects/HEEPsilon/sw/device/lib/base/freestanding     -I /home/benoit/ESL/Projects/HEEPsilon/sw/device/lib/base/freestanding     -I /home/benoit/ESL/Projects/HEEPsilon/sw/device/lib/base/freestanding     -I /home/benoit/ESL/Projects/HEEPsilon/sw/device/lib/base/freestanding     -I /home/benoit/ESL/Projects/HEEPsilon/sw/device/lib/base/freestanding     -I /home/benoit/ESL/Projects/HEEPsilon/sw/device/lib/base/freestanding     -I /home/benoit/ESL/Projects/HEEPsilon/sw/device/lib/base/freestanding     -I /home/benoit/ESL/Projects/HEEPsilon/sw/device/lib/base/freestanding     -I /home/benoit/ESL/Projects/HEEPsilon/sw/device/lib/base     -I /home/benoit/ESL/Projects/HEEPsilon/sw/device/lib/base     -I /home/benoit/ESL/Projects/HEEPsilon/sw/device/lib/base     -I /home/benoit/ESL/Projects/HEEPsilon/sw/device/lib/base     -I /home/benoit/ESL/Projects/HEEPsilon/sw/device/lib/base     -I /home/benoit/ESL/Projects/HEEPsilon/sw/device/lib/drivers/ams     -I /home/benoit/ESL/Projects/HEEPsilon/sw/device/lib/drivers/dma     -I /home/benoit/ESL/Projects/HEEPsilon/sw/device/lib/drivers/dma     -I /home/benoit/ESL/Projects/HEEPsilon/sw/device/lib/drivers/dma     -I /home/benoit/ESL/Projects/HEEPsilon/sw/device/lib/drivers/fast_intr_ctrl     -I /home/benoit/ESL/Projects/HEEPsilon/sw/device/lib/drivers/fast_intr_ctrl     -I /home/benoit/ESL/Projects/HEEPsilon/sw/device/lib/drivers/fast_intr_ctrl     -I /home/benoit/ESL/Projects/HEEPsilon/sw/device/lib/drivers/gpio     -I /home/benoit/ESL/Projects/HEEPsilon/sw/device/lib/drivers/gpio     -I /home/benoit/ESL/Projects/HEEPsilon/sw/device/lib/drivers/gpio     -I /home/benoit/ESL/Projects/HEEPsilon/sw/device/lib/drivers/i2c     -I /home/benoit/ESL/Projects/HEEPsilon/sw/device/lib/drivers/i2c     -I /home/benoit/ESL/Projects/HEEPsilon/sw/device/lib/drivers/i2c     -I /home/benoit/ESL/Projects/HEEPsilon/sw/device/lib/drivers/i2s     -I /home/benoit/ESL/Projects/HEEPsilon/sw/device/lib/drivers/i2s     -I /home/benoit/ESL/Projects/HEEPsilon/sw/device/lib/drivers/i2s     -I /home/benoit/ESL/Projects/HEEPsilon/sw/device/lib/drivers/pad_control     -I /home/benoit/ESL/Projects/HEEPsilon/sw/device/lib/drivers/pad_control     -I /home/benoit/ESL/Projects/HEEPsilon/sw/device/lib/drivers/pdm2pcm     -I /home/benoit/ESL/Projects/HEEPsilon/sw/device/lib/drivers/pdm2pcm     -I /home/benoit/ESL/Projects/HEEPsilon/sw/device/lib/drivers/power_manager     -I /home/benoit/ESL/Projects/HEEPsilon/sw/device/lib/drivers/power_manager     -I /home/benoit/ESL/Projects/HEEPsilon/sw/device/lib/drivers/power_manager     -I /home/benoit/ESL/Projects/HEEPsilon/sw/device/lib/drivers/rv_plic     -I /home/benoit/ESL/Projects/HEEPsilon/sw/device/lib/drivers/rv_plic     -I /home/benoit/ESL/Projects/HEEPsilon/sw/device/lib/drivers/rv_plic     -I /home/benoit/ESL/Projects/HEEPsilon/sw/device/lib/drivers/rv_timer     -I /home/benoit/ESL/Projects/HEEPsilon/sw/device/lib/drivers/rv_timer     -I /home/benoit/ESL/Projects/HEEPsilon/sw/device/lib/drivers/rv_timer     -I /home/benoit/ESL/Projects/HEEPsilon/sw/device/lib/drivers/soc_ctrl     -I /home/benoit/ESL/Projects/HEEPsilon/sw/device/lib/drivers/soc_ctrl     -I /home/benoit/ESL/Projects/HEEPsilon/sw/device/lib/drivers/soc_ctrl     -I /home/benoit/ESL/Projects/HEEPsilon/sw/device/lib/drivers/spi_host     -I /home/benoit/ESL/Projects/HEEPsilon/sw/device/lib/drivers/spi_host     -I /home/benoit/ESL/Projects/HEEPsilon/sw/device/lib/drivers/spi_host     -I /home/benoit/ESL/Projects/HEEPsilon/sw/device/lib/drivers/spi_memio     -I /home/benoit/ESL/Projects/HEEPsilon/sw/device/lib/drivers/spi_memio     -I /home/benoit/ESL/Projects/HEEPsilon/sw/device/lib/drivers/uart     -I /home/benoit/ESL/Projects/HEEPsilon/sw/device/lib/drivers/uart     -I /home/benoit/ESL/Projects/HEEPsilon/sw/device/lib/drivers/uart     -I /home/benoit/ESL/Projects/HEEPsilon/sw/device/lib/runtime     -I /home/benoit/ESL/Projects/HEEPsilon/sw/device/lib/runtime     -I /home/benoit/ESL/Projects/HEEPsilon/sw/device/lib/runtime     -I /home/benoit/ESL/Projects/HEEPsilon/sw/device/lib/runtime     -I /home/benoit/ESL/Projects/HEEPsilon/sw/device/lib/runtime     -I /home/benoit/ESL/Projects/HEEPsilon/sw/device/target/sim     -I /home/benoit/ESL/Projects/HEEPsilon/sw/external/drivers/cgra     -I /home/benoit/ESL/Projects/HEEPsilon/sw/external/drivers/cgra     -I /home/benoit/ESL/Projects/HEEPsilon/sw/external/extensions     
Current project: cgra_size
Root project: /home/benoit/ESL/Projects/HEEPsilon/hw/vendor/esl_epfl_x_heep/sw/
Source path: /home/benoit/ESL/Projects/HEEPsilon/hw/vendor/esl_epfl_x_heep/sw/
LIB_CRT PATH for Cmake: /home/benoit/ESL/Projects/HEEPsilon/hw/vendor/esl_epfl_x_heep/sw/device/lib/crt/
LINKER File for Cmake: link.ld
LIB_DRIVERS PATH for Cmake: 
Targetting folder: /home/benoit/ESL/Projects/HEEPsilon/hw/vendor/esl_epfl_x_heep/sw/device/target/sim/
Target: sim
Linked files: /home/benoit/ESL/Projects/HEEPsilon/hw/vendor/esl_epfl_x_heep/sw/device/lib/crt/crt0.S                      /home/benoit/ESL/Projects/HEEPsilon/hw/vendor/esl_epfl_x_heep/sw/device/lib/crt/vectors.S                      /home/benoit/ESL/Projects/HEEPsilon/hw/vendor/esl_epfl_x_heep/sw/device/lib/base/bitfield.c    /home/benoit/ESL/Projects/HEEPsilon/hw/vendor/esl_epfl_x_heep/sw/device/lib/base/memory.c    /home/benoit/ESL/Projects/HEEPsilon/hw/vendor/esl_epfl_x_heep/sw/device/lib/base/mmio.c    /home/benoit/ESL/Projects/HEEPsilon/hw/vendor/esl_epfl_x_heep/sw/device/lib/drivers/dma/dma.c    /home/benoit/ESL/Projects/HEEPsilon/hw/vendor/esl_epfl_x_heep/sw/device/lib/drivers/fast_intr_ctrl/fast_intr_ctrl.c    /home/benoit/ESL/Projects/HEEPsilon/hw/vendor/esl_epfl_x_heep/sw/device/lib/drivers/gpio/gpio.c    /home/benoit/ESL/Projects/HEEPsilon/hw/vendor/esl_epfl_x_heep/sw/device/lib/drivers/i2c/i2c.c    /home/benoit/ESL/Projects/HEEPsilon/hw/vendor/esl_epfl_x_heep/sw/device/lib/drivers/i2s/i2s.c    /home/benoit/ESL/Projects/HEEPsilon/hw/vendor/esl_epfl_x_heep/sw/device/lib/drivers/pad_control/pad_control.c    /home/benoit/ESL/Projects/HEEPsilon/hw/vendor/esl_epfl_x_heep/sw/device/lib/drivers/power_manager/power_manager.c    /home/benoit/ESL/Projects/HEEPsilon/hw/vendor/esl_epfl_x_heep/sw/device/lib/drivers/rv_plic/rv_plic.c    /home/benoit/ESL/Projects/HEEPsilon/hw/vendor/esl_epfl_x_heep/sw/device/lib/drivers/rv_timer/rv_timer.c    /home/benoit/ESL/Projects/HEEPsilon/hw/vendor/esl_epfl_x_heep/sw/device/lib/drivers/soc_ctrl/soc_ctrl.c    /home/benoit/ESL/Projects/HEEPsilon/hw/vendor/esl_epfl_x_heep/sw/device/lib/drivers/spi_host/spi_host.c    /home/benoit/ESL/Projects/HEEPsilon/hw/vendor/esl_epfl_x_heep/sw/device/lib/drivers/uart/uart.c    /home/benoit/ESL/Projects/HEEPsilon/hw/vendor/esl_epfl_x_heep/sw/device/lib/runtime/handler.c    /home/benoit/ESL/Projects/HEEPsilon/hw/vendor/esl_epfl_x_heep/sw/device/lib/runtime/init.c    /home/benoit/ESL/Projects/HEEPsilon/hw/vendor/esl_epfl_x_heep/sw/device/lib/runtime/syscalls.c    
Linker file: /home/benoit/ESL/Projects/HEEPsilon/hw/vendor/esl_epfl_x_heep/sw/linker/link.ld
Lib Folder RISCV-GCC: /home/benoit/Tools/riscv/riscv32-unknown-elf/lib
-- Configuring done
CMake Error at CMakeLists.txt:233 (add_executable):
  Cannot find source file:

    /home/benoit/ESL/Projects/HEEPsilon/hw/vendor/esl_epfl_x_heep/sw/applications/cgra_size/main.c

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .mpp .m .M .mm .ixx .cppm .h
  .hh .h++ .hm .hpp .hxx .in .txx .f .F .for .f77 .f90 .f95 .f03 .hip .ispc


CMake Error at CMakeLists.txt:233 (add_executable):
  No SOURCES given to target: main.elf


CMake Generate step failed.  Build files cannot be regenerated correctly.
make[2]: *** [cmake/targets.mak:26: build/Makefile] Error 1
make[2]: Leaving directory '/home/benoit/ESL/Projects/HEEPsilon/hw/vendor/esl_epfl_x_heep/sw'
make[1]: *** [Makefile:118: app] Error 2
make[1]: Leaving directory '/home/benoit/ESL/Projects/HEEPsilon/hw/vendor/esl_epfl_x_heep'
make: *** [hw/vendor/esl_epfl_x_heep//external.mk:52: app] Error 2

**Comment by davidmallasen** [comment]
This was an issue that happened before but with the latest commits it works fine for me (I also had to add empty header files before). Are you using an older commit of X-HEEP @benoitdenkinger ?

**Comment by benoitdenkinger** [comment]
Hi @davidmallasen, the problem is now solved with the newest xheep version vendorized. Thanks!
