### ISSUE TITLE
memset should be called before the return in example_spi APPs

### ISSUE THREAD

**Issue by davideschiavone** [esl-epfl/x-heep#438]
resetting the buffer to 0 must happen before the return, otherwise it never gets executed 

https://github.com/esl-epfl/x-heep/blob/main/sw/applications/example_spi_read/main.c#L123

@consanii

**Comment by consanii** [comment]
My bad, I fixed it.

**Comment by davideschiavone** [comment]
> My bad, I fixed it.

can you please open the pull request?

**Comment by davideschiavone** [comment]
#439
