### ISSUE TITLE
MATCHES statements in CMakeLists.txt may lead to false positives and cause the wrong target to be built

### ISSUE THREAD

**Issue by StMiky** [esl-epfl/x-heep#468]
## Description
The `MATCHES` statements in `sw/CMakeLists` succeed with any absolute file path containing the word assigned to `$TARGET`, even before the `sw/device/target/` part of the path. When this happens, multiple include paths for `x-heep.h` are passed to the compiler, causing the wrong headers to be used in the build process.

## Example
Assume a poor X-HEEP user is called _Simon_. Simon's user name on the server where he cloned the X-HEEP repository is `simon.hellodarkness`. Therefore, each file in the lists defined by `cmake` will contain the substring `/home/simon.hellodarkness/<path-to-xheep>/` in its full path, and therefore the `sim` string. If Simon decides to build an app with the default target `TARGET=sim`, the `MATCHES` statement at [this line](https://github.com/esl-epfl/x-heep/blob/01c514c19ef95b050a7f77141435c452a8242bd2/sw/CMakeLists.txt#L68) of `CMakeLists.txt` will match all his files in `/home/simon.hellodarkness/<path-to-xheep>/sw/*`, including all three `x-heep.h` headers from `sw/target/nexys-a7-100t/`, `sw/target/pynq-z2/` and `sw/target/sim/`. Because `nexys-a7-100t` comes first in alphabetical order, the FPGA `x-heep.h` is used in the build process in place of the one in `target/sim/`.

### Reproduce
```bash
mkdir poor-simon && cd poor-simon
git clone https://github.com/esl-epfl/x-heep.git
cd x-heep
make mcu-gen
make app PROJECT=hello_world TARGET=sim # note the pragma messages reporting the wrong header being used
```

## Solution
Because there is a remote possibility that Simon refuses to change his name, it is probably better to implement stricter match patterns in `CMakeLists.txt`. A pull request with a tentative solution is already being prepared.

**Comment by JuanSapriza** [comment]
I think you make a very relevant point about the level of commitment we wxpect from our X-HEEP users. Maybe we should review that policy hahaha 

I think this should be solvable through #469
