### ISSUE TITLE
example_cpp: Main C code not executing linked C++ code

### ISSUE THREAD

**Issue by ShowiGore** [esl-epfl/x-heep#492]
### Description:
The main C code (main.c) in the project is failing to execute the linked C++ code (test_cpp.cpp). Specifically, the function test_numbers() defined in test_cpp.cpp is not being called or executed from main.c.

### Steps to Reproduce:
1. Compile and run the project.
2. Observe that the output only includes "hello world!" from main.c and doesn't include the output from test_numbers() in test_cpp.cpp.

### Expected Behavior:
The main C code should execute the linked C++ code, including the function test_numbers() from test_cpp.cpp.

### Actual Behavior:
Only the output from main.c is observed, indicating that the C++ code is not being executed.

**Comment by JoseCalero** [comment]
this is being fixed in PR #518
