### ISSUE TITLE
Dynamic memory allocation not working

### ISSUE THREAD

**Issue by LinusCrugnola** [esl-epfl/x-heep#513]
Dynamic memory allocation using malloc() does return weird results, I provide a quick fix that deals with some of the problems in [this pr](https://github.com/esl-epfl/x-heep/pull/512) But there are still issues.
---
Note: the original problem is explained in the md file in the first commit attached to the [pr](https://github.com/esl-epfl/x-heep/pull/512)
Note: the quick fix is in the second commit attached to the same pr

**Comment by davideschiavone** [comment]
#543 fixed this. @LinusCrugnola , in case you still have issues pls reopen this ISSUE
