### ISSUE TITLE
Formatting issues on DMA.md

### ISSUE THREAD

**Issue by cousteaulecommandant** [esl-epfl/x-heep#566]
I found the following issues in [docs/source/Peripherals/DMA.md](https://github.com/esl-epfl/x-heep/blob/main/docs/source/Peripherals/DMA.md?plain=1):
* Most lines have double spacing (or, in the case of lines that *need* the double spacing, they have quadruple spacing).
* Indentation has disappeared.
* There are some unresolved merge conflicts left in the file (`<<<<<<<` `=======` `>>>>>>>`).

The first two are specially annoying for code snippets, and may have caused the third one.

Overall, it seems that the file got mangled at some point by some code editor or a code copy-paste gone wrong.

Could someone please try to fix that file?

**Comment by davideschiavone** [comment]
@JuanSapriza @TommiTerza

**Comment by JuanSapriza** [comment]
Thanks @cousteaulecommandant for noticing!! Will get to it right now
