### ISSUE TITLE
missing EXTERNAL CRT0 define when compiling internal HEEP apps

### ISSUE THREAD

**Issue by LuigiGiuffrida98** [esl-epfl/x-heep#585]
when compiling X-HEEP applications inside a project that vendorizes x-heep, the external crt0 does not get included

**Comment by davideschiavone** [comment]
in my opinion, it the file exists (external crt0) then it should always be included, regardless whether the APP is internal or not @JoseCalero

**Comment by JoseCalero** [comment]
totally agree with @davideschiavone, i will take a look at the cmake backend

**Comment by davideschiavone** [comment]
thanks @JoseCalero

**Comment by davideschiavone** [comment]
@JoseCalero , any news on this?

**Comment by JoseCalero** [comment]
#592 
Done, CMake monster got another head more, it is starting to look like an Hydra

**Comment by davideschiavone** [comment]
2c6d7d8f581020d4961bd08dbd3956c90b676085
