### ISSUE TITLE
Error in the Docs ：sw\applications\blinky_freertos -> sw\applications\example_freertos_blinky

### ISSUE THREAD

**Issue by dsjdx** [esl-epfl/x-heep#604]
![image](https://github.com/user-attachments/assets/d05d6000-a697-428e-bc32-f2929802da61)
I think blinky_freertos should be modified to example_freertos_blinky

**Comment by davidmallasen** [comment]
Hello @dsjdx. Thanks for reporting this. You are right that the name should be changed. Could you open a pull request with that change?

**Comment by dsjdx** [comment]
OK, pull request has been made
