### ISSUE TITLE
implement I2S and PDM peripherals 

### ISSUE THREAD

**Issue by JoseCalero** [esl-epfl/x-heep#88]
Amongst the vast amount of modalities when dealing with wearables, audio and speech are essential. In fact, they are not only used in wearables but in many other known day-to-day devices/systems (Alexa, Google Nest, etc.). Within this context, being ultra-low-power and low-cost, x-heep does not implement any I2S and/or PDM peripherals yet. Note that these are the main interfaces when dealing with microphones. Thus, designing and implementing those within x-heep is desired. Moreover, they will be validated by means of behavioral simulation and tested using a pre-trained neural network for keyword spotting speech recognition.

**Comment by davideschiavone** [comment]
* PDM in progress

**Comment by davideschiavone** [comment]
PDM filter has still bugs but i2s is now implemented #203
