### ISSUE TITLE
add 8b and 16b capabality to the DMA

### ISSUE THREAD

**Issue by davideschiavone** [esl-epfl/x-heep#93]

**Comment by davideschiavone** [comment]
@ruben-roalvarez

**Comment by ruben-roalvarez** [comment]
The DMA transactions are more efficient with 32-bit. Usually, 8-bit and 16-bit capabilities are useful when used in peripherals (where the data coming from sensors might have these formats), but adding this to the DMA will add more complex logic and byte data swapping. The best solution here is to collect an entire word in HW before sending it to the memory. However, this is already performed by the SPI_HOST peripheral we are using.

It may be useful to configure only the byte_enables of the words being copied in the memory to have more freedom from the SW
