### ISSUE TITLE
peripherals interrupt connected to fast interrupt ? e.g. #16

### ISSUE THREAD

**Issue by davideschiavone** [esl-epfl/x-heep#95]
for example the DMA can be connected to fast interrupts, but also a second timer, or SPI, etc, we should decide which interrupts are "FAST"

**Comment by davideschiavone** [comment]
@benoitdenkinger @simone-machetti @ruben-roalvarez

**Comment by benoitdenkinger** [comment]
I don't know how much faster it would be, but it makes sense if the platform relies a lot on the DMA. I can implement it.

**Comment by simone-machetti** [comment]
Solved.

**Comment by simone-machetti** [comment]
Interrupt assigned as follow:

Always-on peripherals:

-     soc_cntr: no interrupt
-     boot_rom: no interrupt
-     spi_subsystem: irq_fast[4]
-     power_manager: no interrupt
-     rv_timer_0: irq_timer
-     rv_timer_1: irq_fast[0]
-     dma: irq_fast[3]

On-off peripherals:

-     rv_plic: irq_external
-     uart: plic[8:1]
-     gpio: plic[32:9] - irq_fast[12:5]
-     i2c: plic[48:33]
-     rv_timer_0: irq_fast[1]
-     rv_timer_1: irq_fast[2]
