### ISSUE TITLE
having 2 timers ? one for scheduler and one DMA, maybe more ?

### ISSUE THREAD

**Issue by davideschiavone** [esl-epfl/x-heep#96]

**Comment by davideschiavone** [comment]
@benoitdenkinger @simone-machetti @ruben-roalvarez

**Comment by simone-machetti** [comment]
I am adding 2 timers into the always-on domain and 2 timers into the on/off domain. They should be enough. @benoitdenkinger and @ruben-roalvarez, you can skip this issue.

**Comment by simone-machetti** [comment]
Solved.
